### ISSUE TITLE
README.md does not specify DevExpress libraries needed to build

### ISSUE THREAD

**Issue by jakehappersett** [dragnilar/Databvase#40]
Assuming you are building from source knowing which specific libraries to grab would be beneficial

**Comment by dragnilar** [comment]
I agree. I will add them tomorrow. For the time being here is the list (courtesy of the .CSPROJ file).

   DevExpress.BonusSkins.v18.1
    DevExpress.Charts.v18.1.Core
    DevExpress.CodeParser.v18.1
    DevExpress.Dashboard.v18.1.Core
    DevExpress.Dashboard.v18.1.Win
    DevExpress.Data.v18.1
    DevExpress.DataAccess.v18.1
    DevExpress.DataAccess.v18.1.UI
    DevExpress.Images.v18.1
    DevExpress.Map.v18.1.Core
    DevExpress.Mvvm.v18.1
    DevExpress.Office.v18.1.Core
    DevExpress.PivotGrid.v18.1.Core
    DevExpress.Printing.v18.1.Core
    DevExpress.RichEdit.v18.1.Core
    DevExpress.Sparkline.v18.1.Core
    DevExpress.TreeMap.v18.1.Core
    DevExpress.Utils.v18.1
    DevExpress.Utils.v18.1.UI
    DevExpress.Xpo.v18.1
    DevExpress.XtraBars.v18.1
    DevExpress.XtraCharts.v18.1
    DevExpress.XtraCharts.v18.1.UI
    DevExpress.XtraCharts.v18.1.Wizard
    DevExpress.XtraDialogs.v18.1
    DevExpress.XtraEditors.v18.1
    DevExpress.XtraGauges.v18.1.Core
    DevExpress.XtraGauges.v18.1.Presets
    DevExpress.XtraGauges.v18.1.Win
    DevExpress.XtraGrid.v18.1
    DevExpress.XtraLayout.v18.1
    DevExpress.XtraMap.v18.1
    DevExpress.XtraPivotGrid.v18.1
    DevExpress.XtraPrinting.v18.1
    DevExpress.XtraReports.v18.1.Extensions
    DevExpress.XtraReports.v18.1
    DevExpress.XtraRichEdit.v18.1
    DevExpress.XtraRichEdit.v18.1.Extensions
    DevExpress.XtraTreeList.v18.1
    DevExpress.XtraTreeMap.v18.1
    DevExpress.XtraWizard.v18.1

It should probably be noted also that they will all have to be at least version 18.1.5 or above (soon).

**Comment by dragnilar** [comment]
Readme has been updated with the list of libraries.
